[package]
name = "mscg_server"
version = "0.1.0"
edition = "2024"

[dependencies]
rhai = "1.22.2"
prost = "0.14"
prost-types = "0.14"
crc32fast = "1.5.0"
anyhow = "1.0"
bytes = "1"
spire_enum = "0.7.1"
log = "0.4"
tklog = "0.3.0"

[build-dependencies]
prost-build = "0.14"
