hard_tabs = true
max_width = 120

# brace_style = "AlwaysNextLine"
# control_brace_style = "AlwaysNextLine"
# binop_separator = "Back"
# format_code_in_doc_comments = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Module"
